name: Fetch and Store Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight

jobs:
  fetch_images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch GitHub stats image
      run: |
        curl -o github_stats_image.svg "https://github-readme-stats-khaki-six.vercel.app/api?username=Ahmedsaed&count_private=true&show_icons=true&theme=dark&include_all_commits=true"
        echo "Fetched GitHub stats image"

    - name: Fetch GitHub languages image
      run: |
        curl -o github_languages_image.svg "https://github-readme-stats-khaki-six.vercel.app/api/top-langs/?username=Ahmedsaed&layout=compact&theme=dark&langs_count=6&exclude_repo=fxtips-broker,Deep-Learning-Specialization-Coursera,MachineLearning-StanfordOnline,CS50AI,kaggle,MLH-GHW-Video-Game,Energy-Management-Dashboard,Fix_My_Code_Challenge&hide=html,Jupyter%20Notebook,makefile,css,makefile,Roff,purebasic,scss,less"
        echo "Fetched GitHub languages image"

    - name: Fetch GitHub streak image
      run: |
        curl -o github_streak_image.svg "http://github-readme-streak-stats.herokuapp.com?user=Ahmedsaed&theme=dark&date_format=M%20j%5B%2C%20Y%5D"
        echo "Fetched GitHub streak image"

    - name: Commit and push images
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add github_stats_image.svg github_languages_image.svg github_streak_image.svg
        git commit -m "Update GitHub images [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
